import mongoose, { Schema } from "mongoose";
import { IUser } from "../../utils/userInterface";

const UserSchema: Schema = new Schema(
  {
    email: {
      type: String,
      required: [true, "Email is required"],
      unique: [true, "A user with this email already exists"],
      match: [/\S+@\S+\.\S+/, "Please use a valid email address"],
    },
    username: {
      type: String,
    },
    phone: { type: String, default: "" },
    media: { type: String, default: "" },
    picture: { type: String, default: "" },
    displayName: { type: String, default: "" },
    intro: { type: String, default: "" },
    userId: { type: String, default: "" },
    role: { type: String, default: null },
    signupIp: { type: String, default: "" },
    interests: { type: Array, default: [] },
    userStatus: { type: String, default: "User" },
    staffPositions: { type: String, default: "" },
    residentCountry: { type: String, default: "" },
    postVisibility: { type: String, default: "" },
    commentAbility: { type: String, default: "" },
    residentState: { type: String, default: "" },
    originCountry: { type: String, default: "" },
    origintState: { type: String, default: "" },
    notifications: { type: String, default: "" },
    socials: { type: String, default: "" },
    signupCountry: { type: String, default: "" },
    signupCountryFlag: { type: String, default: "" },
    level: { type: Number, default: 1 },
    followers: { type: Number, default: 0 },
    posts: { type: Number, default: 0 },
    comments: { type: Number, default: 0 },
    uploads: { type: Number, default: 0 },
    exams: { type: Number, default: 0 },
    isOnVerification: { type: Boolean, default: false },
    isVerified: { type: Boolean, default: false },
    isPublic: { type: Boolean, default: false },
    isFollowed: { type: Boolean, default: false },
    isDocument: { type: Boolean, default: false },
    isOrigin: { type: Boolean, default: false },
    isContact: { type: Boolean, default: false },
    isBio: { type: Boolean, default: false },
    isRelated: { type: Boolean, default: false },
    isEducationDocument: { type: Boolean, default: false },
    isEducationHistory: { type: Boolean, default: false },
    isEducation: { type: Boolean, default: false },
    isAccountSet: { type: Boolean, default: false },
    isAccountOpen: { type: Boolean, default: false },
    isSchoolRecorded: { type: Boolean, default: false },
    isSuspendeded: { type: Boolean, default: false },
    isDeleted: { type: Boolean, default: false },
    isFirstTime: { type: Boolean, default: true },
    online: { type: Boolean, default: true },
    leftAt: { type: Date, default: Date.now },
    visitedAt: { type: Date, default: Date.now },
    verifyingAt: { type: Date, default: null },
    verifiedAt: { type: Date, default: Date.now },
    createdAt: { type: Date, default: Date.now },
    passwordResetToken: { type: String, default: null },
    password: {
      type: String,
      required: [true, "Password is required"],
      minlength: [6, "Password must be at least 6 characters long"],
      select: false,
    },
    passwordExpiresAt: { type: Date, default: null },
  },
  {
    timestamps: true,
  }
);

export const User = mongoose.model<IUser>("User", UserSchema);
